AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'dice_bot

  '
Globals:
  Function:
    Timeout: 5
    Runtime: python3.8
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO
        POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
        POWERTOOLS_LOGGER_LOG_EVENT: true
        POWERTOOLS_METRICS_NAMESPACE: MyServerlessApplication
        POWERTOOLS_SERVICE_NAME: hello
        SLACK_WEBHOOK: LOCAL
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: s3://oseikrom-lambda-resources/73d2bdbd6a2ce0ebc6952042b216b334
      Description: Hello World function
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE
      Tags:
        SOLUTION: MyServerlessApplication
        SOLUTION_MODULE: MyHelloWorldFunction
  HelloWorldFunctionAdditionalPermission:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: root
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: ssm:GetParameters
          Resource: '*'
      Roles:
      - Ref: HelloWorldFunctionRole
Outputs:
  HelloWorldApigwURL:
    Description: API Gateway endpoint URL for Prod environment for Hello World Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
